"""add document_id to chat_sessions

Revision ID: c6b75eca055c
Revises: 0005_document_type_and_metadata
Create Date: 2026-08-22 10:29:54.785578

"""
from __future__ import annotations

from typing import Sequence, Union
import app.db.types  # Add this line near the top imports
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b75eca055c'
down_revision: Union[str, None] = '0005_document_type_and_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message_sources', 'position',
               existing_type=sa.INTEGER(),
               comment='1-based citation index in the prompt.',
               existing_nullable=False)
    op.alter_column('chat_message_sources', 'page_number',
               existing_type=sa.INTEGER(),
               comment='1-based page number, when known.',
               existing_nullable=True)
    op.alter_column('chat_message_sources', 'slide_number',
               existing_type=sa.INTEGER(),
               comment='1-based slide number, when known.',
               existing_nullable=True)
    op.create_index(op.f('ix_chat_message_sources_created_at'), 'chat_message_sources', ['created_at'], unique=False)
    op.add_column('chat_sessions', sa.Column('document_id', app.db.types.GUID(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_document_id'), 'chat_sessions', ['document_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_courses_created_at'), 'courses', ['created_at'], unique=False)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_index(op.f('ix_courses_created_at'), table_name='courses')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_document_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'document_id')
    op.drop_index(op.f('ix_chat_message_sources_created_at'), table_name='chat_message_sources')
    op.alter_column('chat_message_sources', 'slide_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1-based slide number, when known.',
               existing_nullable=True)
    op.alter_column('chat_message_sources', 'page_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1-based page number, when known.',
               existing_nullable=True)
    op.alter_column('chat_message_sources', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='1-based citation index in the prompt.',
               existing_nullable=False)
    # ### end Alembic commands ###
